"""AddImageTable

Revision ID: fb64773f3864
Revises: 9d1db7803e04
Create Date: 2025-09-11 10:08:32.452166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb64773f3864'
down_revision = '9d1db7803e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=False))

    # ### end Alembic commands ###
