services:
  web:
    build: .
    container_name: coffeeapp_backend
    stdin_open: true
    tty: true
    volumes:
      - uploads_data:/app/static/uploads
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  uploads_data:
